// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Removed   sql.NullTime
	Name      string
	Amount    string
	ListID    uuid.UUID
}

type List struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Name      string
}
